### ISSUE TITLE
pip aotools package dependency issue (numba)

### ISSUE THREAD

**Issue by joncox123** [AOtools/aotools#59]
I did a 'pip install aotools', but after testing with 'import aotools', I received the error shown below. The solution was to do a 'pip install numba'. However, shouldn't this dependency be corrected with the pip package?

Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aotools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/aotools/__init__.py", line 1, in <module>
    from . import astronomy, functions, image_processing, wfs, turbulence, opticalpropagation
  File "/usr/local/lib/python3.7/dist-packages/aotools/turbulence/__init__.py", line 2, in <module>
    from .infinitephasescreen import *
  File "/usr/local/lib/python3.7/dist-packages/aotools/turbulence/infinitephasescreen.py", line 418, in <module>
    **@numba.jit(nopython=True, parallel=True)
AttributeError: 'NoneType' object has no attribute 'jit**'

**Comment by matthewtownson** [comment]
Yes, this is a missing dependency for aotools now. Thanks for pointing this out, we will update the dependencies in the next week or so to prevent others from running into the same issue.

**Comment by matthewtownson** [comment]
Fixed in v1.0.4.
